# Generated by Django 5.2.2 on 2025-08-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='descricao',
            new_name='nome',
        ),
    ]
