# Generated by Django 5.2.2 on 2025-09-04 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensino', '0004_formaselecao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(auto_now=True, null=True)),
                ('removido_em', models.DateTimeField(null=True)),
                ('nome', models.CharField(max_length=255)),
                ('nome_responsavel', models.CharField(max_length=255, null=True)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=65)),
                ('telefone', models.CharField(max_length=65)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizou_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criou_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensino.curso')),
                ('forma_selecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensino.formaselecao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
