@startuml usecases
  left to right direction

  package "Sistema web" {
    :Usuário: as user
    :Técnico: as tec <<Role>>
    :Administrador: as admin <<Role>>

    /' Usuário '/
    user -l-> (Fazer login)
    user --> (Manter cadastro)

    /' Técnico '/
    "Visualizar dashboard" as (dash)
    "Manter computadores" as (crudcomp)
    tec -l-|> user
    tec --> (Manter softwares)
    tec --> (Manter protótipos)
    tec --> (Manter empréstimos)
    tec --> crudcomp
    tec --> dash
    dash ..> (Visualizar próximos inventários) : <<include>>
    dash ..> (Visualizar inventários pendentes) : <<include>>
    crudcomp ..> (Vincular computador a um protótipo) : <<include>>

    /' Administrador '/
    admin -d-|> tec
    admin -l-> (Manter usuários)
    admin -l-> (Manter roles)
    admin -> (Manter alunos)
  }

  :Aluno: as alu
  alu --> (Receber e-mail de inventário próximo)
  alu --> (Receber e-mail de atualização de imagem)
  alu --> (Receber e-mail de fim de empréstimo)
  :Computador: as comp <<Application>>
  comp --> (Realizar inventário)
@enduml
