@startuml usecases
  left to right direction

  package "Sistema web" {
    :Usuário: as user
    :Membro: as tec <<Role>>
    :Administrador: as admin <<Role>>

    /' Usuário '/
    user -r-> (Fazer login)
    user --> (Manter cadastro)

    /' Técnico '/
    "Manter bens" as (crudbens)
    "Receber notificação" as (notificacao)
    "Realizar empréstimo" as (emp)
    "Registrar ocorrencia" as (oco)
    tec -r-|> user
    tec --> (Manter empréstimos)
    tec --> crudbens
    tec --> notificacao
    tec --> oco
    tec --> emp
    tec --> (Manter tipos de bem)
    tec --> (Manter alunos)
    emp ..> (Gerar termo de responsabilidade) :<<include>>
    emp ..> (Gerar termo de devolução) :<<include>>

    notificacao ..> (Receber notificação de ocorrências) : <<include>>

    /' Administrador '/
    admin -|> tec
    admin --> (Manter usuários)
    admin --> (Manter roles)
    
    admin --> (Manter tipos de ocorrencia)
    admin --> (Manter cursos)
    admin --> (Manter estados de conservação)
  }

  :Aluno: as aluno
  aluno --> (Receber e-mail de fim de empréstimo)
@enduml
