@startuml usecases
  left to right direction

  package "Sistema web" {
    :Usuário: as user
    :Membro: as membro <<Role>>
    :Administrador: as admin <<Role>>

    /' Usuário '/
    rectangle "Autenticação e Perfil" {
        user -r-> (Fazer login)
        user --> (Fazer log-off)
        user --> (Manter cadastro)
    }

    /' Membro '/
    membro -r-|> user
    rectangle "Gestao de Empréstimos" {
        "Visualizar detalhes do empréstimo" as (empdetail)
        membro --> empdetail
        membro --> (Editar empréstimo)
        membro --> (Realizar empréstimo)
        empdetail <.. (Gerar termo de responsabilidade) : <<extend>>
        empdetail <.. (Gerar termo de devolução) : <<extend>>
        empdetail <.. (Alterar estado do empréstimo) : <<extend>>
        empdetail <.. (Registrar ocorrencia) : <<extend>>
    }

    rectangle "Gestao de Ocorrências" {
        "Visualizar detalhes da ocorrência" as (occdetail)
        membro --> (Visualizar lista de ocorrências)
        membro --> occdetail
        membro --> (Receber notificação de ocorrências)
        occdetail <.. (Alterar estado da ocorrencia) : <<extend>>
    }

    rectangle "Cadastros auxiliares" {
        membro --> (Manter bens)
        membro --> (Manter tipos de bem)
        membro --> (Manter alunos)
        membro --> (Manter marcas/modelo)
    }


    /' Administrador '/
    rectangle "Administração" {
        admin -d-|> membro
        admin -u-> (Manter usuários)
        admin -u-> (Manter roles)
        admin -u-> (Manter tipos de ocorrencia)
        admin -u-> (Manter cursos)
        admin -u-> (Manter campi)
        admin -u-> (Manter graus de fragilidade)
        admin -u-> (Manter estados de conservação)
    }
  }

  :Aluno: as aluno
  aluno --> (Receber e-mail de fim de empréstimo)
@enduml
