# Generated by Django 5.2.2 on 2025-09-27 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
        ('ensino', '0005_aluno'),
        ('patrimonio', '0006_bem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(auto_now=True, null=True)),
                ('removido_em', models.DateTimeField(null=True)),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[(1, 'Ativo'), (2, 'Finalizado'), (3, 'Cancelado')], max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizou_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensino.aluno')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patrimonio.bem')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criou_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('devolucao_ciente_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
