# Generated by Django 5.2.2 on 2025-09-28 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_emprestimo'),
        ('ensino', '0005_aluno'),
        ('patrimonio', '0006_bem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensino.aluno'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='bem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.bem'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='devolucao_ciente_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
