# Generated by Django 5.2.2 on 2025-09-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0003_alter_emprestimo_aluno_alter_emprestimo_bem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Ativo'), (2, 'Finalizado'), (3, 'Cancelado')], max_length=50),
        ),
    ]
