# Generated by Django 5.2.6 on 2025-09-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0004_alter_emprestimo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Ativo'), (2, 'Finalizado'), (3, 'Cancelado')]),
        ),
    ]
