# Generated by Django 5.2.6 on 2025-10-03 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0005_alter_emprestimo_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(auto_now=True, null=True)),
                ('removido_em', models.DateTimeField(null=True)),
                ('data_ocorrencia', models.DateField()),
                ('cancelado_em', models.DateField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, null=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizou_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_canceladas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criou_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.emprestimo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.tipoocorrencia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
