# Generated by Django 5.2.6 on 2025-10-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0006_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
