@startuml sigemp-activity
start
repeat
    :Fazer login;
repeat while (usuario autenticado?) is (não) not (sim)

:Solicitar página de dashboard;

:Exibir dashboard;

split
    :Solicitar página
    de listagem de bens;
    repeat
        :Exibir lista de bens;
        split
            :Solicitar página
            de cadstro do bem;
            :Validar formulário;
            if (formulario valido?) then (sim)
                :Exibir mensagem
                de sucesso;
            else (não)
                :Exibir mensagem
                de erro;
            endif
        split again
            :Solicitar página
            de edição do bem;
            if (bem existe?) then (sim)
                :Exibir formulário de edição;
                split
                    :Atualizar bem;
                    if (formulario valido?) then (sim)
                        :Exibir mensagem
                        de sucesso;
                    else (não)
                        :Exibir mensagem
                        de erro;
                    endif
                split again
                    :Remover bem;
                    if (remoção de bem confirmada?) then (sim)
                        :Exibir mensagem
                        de sucesso;
                    else (não)
                        :Exibir mensagem
                        de erro;
                    endif
                end split
            else (não)
                :Exibir mensagem de erro;
            endif
        end split
    repeat while (mais ações?) is (sim) not (não)
split again
    :Solicitar página
    de listagem
    de marca/modelo;
    repeat
        :Exibir lista de marca/modelo;
        split
            :Solicitar página
            de cadastro do marca/modelo;
            if (formulario valido?) then (sim)
                :Exibir mensagem
                de sucesso;
            else (não)
                :Exibir mensagem
                de erro;
            endif
        split again
            :Solicitar página
            de edição do marca/modelo;
            if (marca existe?) then (sim)
                :Exibir página de edição;
                split
                    :Atualizar marca/modelo;
                    if (formulario valido?) then (sim)
                        :Exibir mensagem
                        de sucesso;
                    else (não)
                        :Exibir mensagem
                        de erro;
                    endif
                split again
                    :Remover marca/modelo;
                    if (remoção de marca/modelo confirmada?) then (sim)
                        :Exibir mensagem
                        de sucesso;
                    else (não)
                        :Exibir mensagem
                        de erro;
                    endif
                end split
            else (não)
                :Exibir mensagem de erro;
            endif
        end split
    repeat while (mais ações?) is (sim) not (não)
split again
    :Solicitar página
    de listagem de tipos de bem;
    repeat
        :Exibir lista de tipos de bem;
        split
            :Solicitar página
            de cadastro do tipo de bem;
            if (formulario valido?) then (sim)
                :Exibir mensagem
                de sucesso;
            else (não)
                :Exibir mensagem
                de erro;
            endif
        split again
            :Solicitar página
            de edição do tipo de bem;
            if (tipo de bem existe?) then (sim)
                :Exibir página de edição;
                split
                    :Atualizar tipo de bem;
                    if (formulario valido?) then (sim)
                        :Exibir mensagem
                        de sucesso;
                    else (não)
                        :Exibir mensagem
                        de erro;
                    endif
                split again
                    :Remover tipo de bem;
                    if (remoção de tipo de bem confirmada?) then (sim)
                        :Exibir mensagem
                        de sucesso;
                    else (não)
                        :Exibir mensagem
                        de erro;
                    endif
                end split
            else (não)
                :Exibir mensagem de erro;
            endif
        end split
    repeat while (mais ações?) is (sim) not (não)
split again
    :Solicitar página
    de listagem graus
    de fragilidade;
    repeat
        :Exibir lista de graus de fragilidade;
        split
            :Solicitar página
            de cadastro do grau de fragilidade;
            if (usuário tem permissão?) then (sim)
                if (formulario valido?) then (sim)
                    :Exibir mensagem
                    de sucesso;
                else (não)
                    :Exibir mensagem
                    de erro;
                endif
            else (não)
                :Exibir mensagem
                de erro;
            endif
        split again
            :Solicitar página
            de edição do grau de fragilidade;
            if (usuário tem permissão?) then (sim)
                if (grau de fragilidade existe?) then (sim)
                    :Exibir página de edição;
                    split
                        :Atualizar grau de fragilidade;
                        if (formulario valido?) then (sim)
                            :Exibir mensagem
                            de sucesso;
                        else (não)
                            :Exibir mensagem
                            de erro;
                        endif
                    split again
                        :Remover grau de fragilidade;
                        if (remoção de grau de fragilidade confirmada?) then (sim)
                            :Exibir mensagem
                            de sucesso;
                        else (não)
                            :Exibir mensagem
                            de erro;
                        endif
                    end split
                    repeat
                    repeat while (mais ações?) is (sim) not (não)
                else (não)
                    :Exibir mensagem de erro;
                endif
            else (não)
                :Exibir mensagem
                de erro;
            endif
        end split
    repeat while (mais ações?) is (sim) not (não)
split again
    :Solicitar página de listagem
    de estados de conservação;
    repeat
        :Exibir lista de estados de conservação;
        split
            :Solicitar página
            de cadastro do estado de conservação;
            if (usuário tem permissão?) then (sim)
                if (formulario valido?) then (sim)
                    :Exibir mensagem
                    de sucesso;
                else (não)
                    :Exibir mensagem
                    de erro;
                endif
            else (não)
                :Exibir mensagem
                de erro;
            endif
        split again
            :Solicitar página
            de edição do estado de conservação;
            if (usuário tem permissão?) then (sim)
                if (estado de conservação existe?) then (sim)
                    :Exibir página de edição;
                    split
                        :Atualizar estado de conservação;
                        if (formulario valido?) then (sim)
                            :Exibir mensagem
                            de sucesso;
                        else (não)
                            :Exibir mensagem
                            de erro;
                        endif
                    split again
                        :Remover estado de conservação;
                        if (remoção de estado de conservação confirmada?) then (sim)
                            :Exibir mensagem
                            de sucesso;
                        else (não)
                            :Exibir mensagem
                            de erro;
                        endif
                    end split
                    repeat
                    repeat while (mais ações?) is (sim) not (não)
                else (não)
                    :Exibir mensagem de erro;
                endif
            else (não)
                :Exibir mensagem
                de erro;
            endif
        end split
    repeat while (mais ações?) is (sim) not (não)
split again
    :Solicitar página de listagem
    de tipos de ocorrência;
    repeat
        :Exibir lista de tipos de ocorrência;
        split
            :Solicitar página
            de cadastro do tipo de ocorrência;
            if (usuário tem permissão?) then (sim)
                if (formulario valido?) then (sim)
                    :Exibir mensagem
                    de sucesso;
                else (não)
                    :Exibir mensagem
                    de erro;
                endif
            else (não)
                :Exibir mensagem
                de erro;
            endif
        split again
            :Solicitar página
            de edição do tipo de ocorrência;
            if (usuário tem permissão?) then (sim)
                if (tipo de ocorrência existe?) then (sim)
                    :Exibir página de edição;
                    split
                        :Atualizar tipo de ocorrência;
                        if (formulario valido?) then (sim)
                            :Exibir mensagem
                            de sucesso;
                        else (não)
                            :Exibir mensagem
                            de erro;
                        endif
                    split again
                        :Remover tipo de ocorrência;
                        if (remoção de tipo de ocorrência confirmada?) then (sim)
                            :Exibir mensagem
                            de sucesso;
                        else (não)
                            :Exibir mensagem
                            de erro;
                        endif
                    end split
                    repeat
                    repeat while (mais ações?) is (sim) not (não)
                else (não)
                    :Exibir mensagem de erro;
                endif
            else (não)
                :Exibir mensagem
                de erro;
            endif
        end split
    repeat while (mais ações?) is (sim) not (não)
split again
    :Solicitar página de listagem de campi;
    repeat
        :Exibir lista de campi;
        split
            :Solicitar página
            de cadastro do campus;
            if (usuário tem permissão?) then (sim)
                if (formulario valido?) then (sim)
                    :Exibir mensagem
                    de sucesso;
                else (não)
                    :Exibir mensagem
                    de erro;
                endif
            else (não)
                :Exibir mensagem
                de erro;
            endif
        split again
            :Solicitar página
            de edição do campus;
            if (usuário tem permissão?) then (sim)
                if (campus existe?) then (sim)
                    :Exibir página de edição;
                    split
                        :Atualizar campus;
                        if (formulario valido?) then (sim)
                            :Exibir mensagem
                            de sucesso;
                        else (não)
                            :Exibir mensagem
                            de erro;
                        endif
                    split again
                        :Remover campus;
                        if (remoção de campus confirmada?) then (sim)
                            :Exibir mensagem
                            de sucesso;
                        else (não)
                            :Exibir mensagem
                            de erro;
                        endif
                    end split
                    repeat
                    repeat while (mais ações?) is (sim) not (não)
                else (não)
                    :Exibir mensagem de erro;
                endif
            else (não)
                :Exibir mensagem
                de erro;
            endif
        end split
    repeat while (mais ações?) is (sim) not (não)
split again
    :Solicitar página de listagem de cursos;
    repeat
        :Exibir lista de cursos;
        split
            :Solicitar página
            de cadastro do aluno;
            if (usuário tem permissão?) then (sim)
                if (formulario valido?) then (sim)
                    :Exibir mensagem
                    de sucesso;
                else (não)
                    :Exibir mensagem
                    de erro;
                endif
            else (não)
                :Exibir mensagem
                de erro;
            endif
        split again
            :Solicitar página
            de edição do curso;
            if (usuário tem permissão?) then (sim)
                if (curso existe?) then (sim)
                    :Exibir página de edição;
                    split
                        :Atualizar curso;
                        if (formulario valido?) then (sim)
                            :Exibir mensagem
                            de sucesso;
                        else (não)
                            :Exibir mensagem
                            de erro;
                        endif
                    split again
                        :Remover curso;
                        if (remoção de curso confirmada?) then (sim)
                            :Exibir mensagem
                            de sucesso;
                        else (não)
                            :Exibir mensagem
                            de erro;
                        endif
                    end split
                    repeat
                    repeat while (mais ações?) is (sim) not (não)
                else (não)
                    :Exibir mensagem de erro;
                endif
            else (não)
                :Exibir mensagem
                de erro;
            endif
        end split
    repeat while (mais ações?) is (sim) not (não)
split again
    :Solicitar página de listagem de alunos;
    repeat
        :Exibir lista de alunos;
        split
            :Solicitar página
            de cadastro do aluno;
            if (formulario valido?) then (sim)
                :Exibir mensagem
                de sucesso;
            else (não)
                :Exibir mensagem
                de erro;
            endif
        split again
            :Solicitar página
            de edição do aluno;
            if (aluno existe?) then (sim)
                :Exibir página de edição;
                split
                    :Atualizar aluno;
                    if (formulario valido?) then (sim)
                        :Exibir mensagem
                        de sucesso;
                    else (não)
                        :Exibir mensagem
                        de erro;
                    endif
                split again
                    :Remover aluno;
                    if (remoção de aluno confirmada?) then (sim)
                        :Exibir mensagem
                        de sucesso;
                    else (não)
                        :Exibir mensagem
                        de erro;
                    endif
                end split
            else (não)
                :Exibir mensagem de erro;
            endif
        end split
    repeat while (mais ações?) is (sim) not (não)
split again
    repeat
    :Solicitar página de listagem de membros;
    if (usuario tem permissão?) then (sim)
        :Exibir lista de membros;
        split
            :Solicitar página
            de cadastro do membro;
            if (formulario valido?) then (sim)
                :Exibir mensagem
                de sucesso;
            else (não)
                :Exibir mensagem
                de erro;
            endif
        split again
            :Solicitar página
            de edição do membro;
            if (membro existe?) then (sim)
                :Exibir página de edição;
                split
                    :Atualizar membro;
                    if (formulario valido?) then (sim)
                        :Exibir mensagem
                        de sucesso;
                    else (não)
                        :Exibir mensagem
                        de erro;
                    endif
                split again
                    :Remover membro;
                    if (remoção de membro confirmada?) then (sim)
                        :Exibir mensagem
                        de sucesso;
                    else (não)
                        :Exibir mensagem
                        de erro;
                    endif
                end split
            else (não)
                :Exibir mensagem de erro;
            endif
        end split
    else (não)
        :Exibir mensagem de erro;
    endif
    repeat while (mais ações?) is (sim) not (não)
split again
    :Solicitar página de listagem de empréstimos;
    repeat
    :Exibir lista de empréstimos;
    split
        :Solicitar página de registro de empréstimo;
            :Registrar novo de empréstimo;
            repeat
            :Validar formulário;
            if (Aluno tem valido?) then (sim)
                :Exibir mensagem
                de sucesso;
            else (não)
                :Exibir mensagem
                de erro;
            endif
            repeat while (formulário válido?) is (não) not (sim)
    split again
        :Solicitar página de edição de empréstimo;
        if (empréstimo existe?) then (sim)
            :Editar empréstimo;
            if (formulário válido?) then (sim)
                :Exibir mensagem
                de sucesso;
            else (não)
                :Exibir mensagem
                de erro;
            endif
        else (não)
            :Exibir mensagem de erro;
        endif
    end split
    repeat while (mais ações?) is (sim) not (não)
end split
stop
@enduml
