# Generated by Django 5.2.1 on 2025-07-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_estadoconservacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoconservacao',
            name='nivel',
            field=models.IntegerField(default=3, verbose_name='Nível'),
            preserve_default=False,
        ),
    ]
