# Generated by Django 5.1.3 on 2024-11-09 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arch', models.CharField(blank=True, max_length=255, null=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('install_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('device_uid', models.CharField(max_length=255, null=True)),
                ('softwares', models.ManyToManyField(to='ativos.software')),
            ],
        ),
    ]
