# Generated by Django 5.1.2 on 2024-10-27 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arch', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('guid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('install_date', models.DateField(default=datetime.date.today)),
                ('computers', models.ManyToManyField(to='ativos.computer')),
            ],
        ),
    ]
