# Generated by Django 5.1.2 on 2024-10-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='computers',
        ),
        migrations.AddField(
            model_name='computer',
            name='softwares',
            field=models.ManyToManyField(to='ativos.software'),
        ),
    ]
