# Generated by Django 5.1.2 on 2024-10-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_remove_software_computers_computer_softwares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='comments',
        ),
    ]
