# Generated by Django 5.1.2 on 2024-10-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_remove_software_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(max_length=256),
        ),
    ]
