# Generated by Django 5.1.2 on 2024-10-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_alter_software_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
