# Generated by Django 5.1.2 on 2024-10-30 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0006_alter_software_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='install_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
