# Generated by Django 5.1.2 on 2024-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0007_alter_software_install_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='arch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='guid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
